name: Entrypoint Main
run-name: Entrypoint main by @${{ github.actor }}

on:
  push:
    branches: [main]

jobs:
  get-application-changes:
    name: Get Files with changes
    uses: ./.github/workflows/reusable-get-application-changes.yaml
    with:
      working-directory: src

  get-infra-changes:
    name: Get Files with changes
    uses: ./.github/workflows/reusable-get-infra-changes.yaml
    with:
      working-directory: infra

  deploy-infra-to-tst:
    name: Deploy Cognito Infrastructure to Test
    needs: [get-application-changes, get-infra-changes]
    if: |
      (needs.get-application-changes.outputs.changed-files != '[]' ||
       needs.get-infra-changes.outputs.changed-files != '[]') &&
      !failure() &&
      !cancelled()
    uses: ./.github/workflows/reusable-deploy-infra.yaml
    with:
      environment: test
      stage: tst
    secrets: inherit

  deploy-infra-to-acc:
    name: Deploy Cognito Infrastructure to Acceptance
    needs: [deploy-infra-to-tst, get-application-changes, get-infra-changes]
    if: |
      (needs.get-application-changes.outputs.changed-files != '[]' ||
       needs.get-infra-changes.outputs.changed-files != '[]') &&
      !failure() &&
      !cancelled()
    uses: ./.github/workflows/reusable-deploy-infra.yaml
    with:
      environment: acceptance
      stage: acc
    secrets: inherit

  deploy-infra-to-prd:
    name: Deploy Cognito Infrastructure to Production
    needs: [deploy-infra-to-acc, get-application-changes, get-infra-changes]
    if: |
      (needs.get-application-changes.outputs.changed-files != '[]' ||
       needs.get-infra-changes.outputs.changed-files != '[]') &&
      !failure() &&
      !cancelled()
    uses: ./.github/workflows/reusable-deploy-infra.yaml
    with:
      environment: production
      stage: prd
    secrets: inherit
