name: Entrypoint Main
run-name: Entrypoint main by @${{ github.actor }}

on:
  push:
    branches: [main]

jobs:
  get-files-with-changes:
    name: Get Files with changes
    uses: ./.github/workflows/reusable-get-files-with-changes.yaml
    with:
      working-directory: src

  deploy-infra-to-tst:
    name: Deploy Cognito Infrastructure to Test
    needs: get-files-with-changes
    if: needs.get-files-with-changes.outputs.changed-files != '[]' && !failure() && !cancelled()
    uses: ./.github/workflows/reusable-deploy-infra.yaml
    with:
      package-path: infra/federated-engineers-portal
      environment: test
      stage: tst
    secrets: inherit

  deploy-infra-to-acc:
    name: Deploy Cognito Infrastructure to Acceptance
    needs: deploy-infra-to-tst
    if: needs.get-files-with-changes.outputs.changed-files != '[]' && !failure() && !cancelled()
    uses: ./.github/workflows/reusable-deploy-infra.yaml
    with:
      package-path: infra/federated-engineers-portal
      environment: acceptance
      stage: acc
    secrets: inherit

  deploy-infra-to-prd:
    name: Deploy Cognito Infrastructure to Production
    needs: deploy-infra-to-acc
    if: needs.get-files-with-changes.outputs.changed-files != '[]' && !failure() && !cancelled()
    uses: ./.github/workflows/reusable-deploy-infra.yaml
    with:
      package-path: infra/federated-engineers-portal
      environment: production
      stage: prd
    secrets: inherit
