name: Entrypoint Feature
run-name: Entrypoint feature by @${{ github.actor }}

on:
  pull_request:
    branches: [main]

jobs:
  get-files-with-changes:
    name: Get Files with changes
    uses: ./.github/workflows/reusable-get-files-with-changes.yaml
    with:
      working-directory: src

  check-if-application-version-is-bumped:
    name: Check if the application version is bumped
    needs: get-files-with-changes
    if: needs.get-files-with-changes.outputs.changed-files != '[]'
    uses: ./.github/workflows/reusable-check-package-version-bumping.yaml
    with:
      working-directory: src

  deploy-infra:
    name: Deploy Cognito Infrastructure to Development
    needs: [get-files-with-changes, check-if-application-version-is-bumped]
    if: needs.get-files-with-changes.outputs.changed-files != '[]' &&
      !failure() &&
      !cancelled()
    uses: ./.github/workflows/reusable-deploy-infra.yaml
    with:
      environment: development
      stage: dev
      application-version: ${{ needs.check-if-application-version-is-bumped.outputs.current-version }}
    secrets: inherit
