name: Detect files with changes

on:
  workflow_call:
    outputs:
      changed-files:
        description: Files with changes
        value: ${{ jobs.changes.outputs.files }}

jobs:
  changes:
    name: Detect files with changes
    runs-on: ubuntu-latest
    outputs:
      files: ${{ steps.filters.outputs.changes }}
    steps:
      - uses: actions/checkout@v4
      - uses: dorny/paths-filter@0bc4621a3135347011ad047f9ecf449bf72ce2bd  # 3.0.0
        id: filters
        with:
          filters: |
            dependency_injection:
              - 'src/dependency_injection/*.py'
            jinja_templates:
              - 'src/jinja_templates/*.html'
            models:
              - 'src/models/*.py'
            services:
              - 'src/services/*.py'
            root:
              - 'src/docker-compose.yml'
              - 'src/Dockerfile'
              - 'src/main.py'
              - 'src/pyproject.toml'
