name: Check if a package version is bumped

on:
  workflow_call:
    inputs:
      working-directory:
        description: 'Directory where the application is located'
        required: false
        default: '.'
        type: string  # Add the type field

jobs:
  check-version:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout current branch
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
          path: ${{ inputs.working-directory }}

      - name: Checkout main branch
        uses: actions/checkout@v4
        with:
          ref: main
          path: main_branch

      - name: Compare and set versions
        id: compare_versions
        run: |
          current_version=$(grep "^version" ${{ inputs.working-directory }}/pyproject.toml | head -n 1 | cut -d '"' -f 2)
          main_version=$(grep "^version" main_branch/${{ inputs.working-directory }}/pyproject.toml | head -n 1 | cut -d '"' -f 2)

          echo "Current branch version: $current_version"
          echo "Main branch version: $main_version"

          if [ "$current_version" = "$main_version" ]; then
              echo "::error ::Version $current_version is equal to $main_version"
              exit 1
          elif [ "$current_version" \< "$main_version" ]; then
              echo "::error ::Version $current_version is less than $main_version"
              exit 1
          else
              echo "::notice ::Version $current_version is greater than $main_version"
              exit 0
          fi
