name: Detect files with changes

on:
  workflow_call:
    inputs:
      working-directory:
        description: 'Directory where the application is located'
        required: false
        default: '.'
        type: string  # Add the type field
    outputs:
      changed-files:
        description: Files with changes
        value: ${{ jobs.changes.outputs.files }}

jobs:
  changes:
    name: Detect files with changes
    runs-on: ubuntu-latest
    outputs:
      files: ${{ steps.filters.outputs.changes }}
    steps:
      - uses: actions/checkout@v4
        with:
          path: ${{ inputs.working-directory }}
          
      - uses: dorny/paths-filter@0bc4621a3135347011ad047f9ecf449bf72ce2bd
        id: filters
        with:
          filters: |
            dependency_injection:
              - '${{ inputs.working-directory }}/dependency_injection/*.py'
            jinja_templates:
              - '${{ inputs.working-directory }}/jinja_templates/*.html'
            models:
              - '${{ inputs.working-directory }}/models/*.py'
            services:
              - '${{ inputs.working-directory }}/services/*.py'
            root:
              - '${{ inputs.working-directory }}/docker-compose.yml'
              - '${{ inputs.working-directory }}/Dockerfile'
              - '${{ inputs.working-directory }}/main.py'
              - '${{ inputs.working-directory }}/pyproject.toml'
