# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: Run mypy and pytest
run-name: Run mypy and pytest by @${{ github.actor }}

on: 
  workflow_call:
    inputs:
      working-directory:
        description: 'Directory where the application is located'
        required: false
        default: '.'

jobs:
  run-mypy-and-pytest:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.12

      - name: Install poetry and dependencies
        run: |
          pipx install poetry
          cd ${{ inputs.working-directory }}  # Ensure poetry is installed in the correct directory
          poetry install
          
      - name: Set up Poetry environment
        run: |
          cd ${{ inputs.working-directory }}  # Use the correct directory
          poetry env use $(which python)

      - name: Set PYTHONPATH
        run: echo "PYTHONPATH=$PYTHONPATH:$(pwd)" >> $GITHUB_ENV

      - name: Run mypy
        run: |
          cd ${{ inputs.working-directory }}  # Run mypy from the correct directory
          poetry run mypy .
      
      - name: Run pytest
        run: |
          cd ${{ inputs.working-directory }}  # Run pytest from the correct directory
          poetry run pytest
